### PR TITLE
Updated empty_block_le.png

### PR DESCRIPTION
**Pull request by dagbay**

### CODE REVIEW

**Comment by dagbay** [comment]
Also added another level and updated pipes_64.png

**Comment by MorgaineBarter** [comment]
I'm trying to find the conflict here, may it be that the files have the same names because the levels currently in the project were recently worked on at the same time,  and so if a change was made it would remove the other change.
I recommend changing the file names, then it shouldn't be a problem
try lvl3_0.txt and lvl3_1.txt :)

**Comment by dagbay** [comment]
I've updated the names but it seems the conflict is still there

**Comment by dagbay** [comment]
FINALLY

**Review by MorgaineBarter — APPROVED** [review]

**Comment by MorgaineBarter** [comment]
well done!

**Pull request merged**
